# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 351ea2aee726ac810508636e20d89a36fee744ffde233e0f3a77f831275d5fc287225b7e6248e993906e66079f492d0d59510b01ef02ecdaae967811f0fc9022

test:
  secret_key_base: 4612938ff010338743a9fdf573dbe6679efac349f62589598b42e35df18f354afa721a64a3a336b45af6a7cf6bede5bd013de08f9842e3273a9e47a451680acd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
